import * as profileApi from './data/profile/index.js'

export const profile = {
	getKey: profileApi.getProfileKey,
	getGroupName: profileApi.getProfileGroupName,
	getKeysForGroup: profileApi.getProfileKeysForGroup,
	getConfigKeys: profileApi.getProfileConfigKeys,
	getString: profileApi.getProfileString,
	setString: profileApi.setProfileString,
	getStringForProfileKey: profileApi.getProfileStringForProfileKey,
	setStringForProfileKey: profileApi.setProfileStringForProfileKey,
	getNumber: profileApi.getProfileNumber,
	getInt: profileApi.getProfileInt,
	getFloat: profileApi.getProfileFloat,
	setNumber: profileApi.setProfileNumber,
	getIntForProfileKey: profileApi.getProfileIntForProfileKey,
	setNumberForProfileKey: profileApi.setProfileNumberForProfileKey,
	getBoolean: profileApi.getProfileBoolean,
	setBoolean: profileApi.setProfileBoolean,
	getBooleanForProfileKey: profileApi.getProfileBooleanForProfileKey,
	setBooleanForProfileKey: profileApi.setProfileBooleanForProfileKey,
	getStringArray: profileApi.getProfileStringArray,
	setStringArray: profileApi.setProfileStringArray,
	getNumberArray: profileApi.getProfileNumberArray,
	setNumberArray: profileApi.setProfileNumberArray,
	getJson: profileApi.getProfileJson,
	setJson: profileApi.setProfileJson,
	unset: profileApi.unsetProfileConfig,
	get: profileApi.getProfileConfig,
	set: profileApi.setProfileConfig,
	logSummary: profileApi.logProfileConfigSummary,
}
